DO $$ BEGIN
    CREATE TYPE wallet_requests_type_enum AS ENUM ('ADD_POINTS', 'WITHDRAW');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
DECLARE
    has_add_points BOOLEAN;
    has_credit BOOLEAN;
    has_withdraw BOOLEAN;
BEGIN
    SELECT EXISTS (
        SELECT 1
        FROM pg_enum e
        JOIN pg_type t ON t.oid = e.enumtypid
        WHERE t.typname = 'wallet_requests_type_enum'
          AND e.enumlabel = 'ADD_POINTS'
    ) INTO has_add_points;
    SELECT EXISTS (
        SELECT 1
        FROM pg_enum e
        JOIN pg_type t ON t.oid = e.enumtypid
        WHERE t.typname = 'wallet_requests_type_enum'
          AND e.enumlabel = 'CREDIT'
    ) INTO has_credit;

    IF has_credit AND NOT has_add_points THEN
        ALTER TYPE wallet_requests_type_enum
            RENAME VALUE 'CREDIT' TO 'ADD_POINTS';
        has_add_points := TRUE;
    ELSIF NOT has_add_points THEN
        ALTER TYPE wallet_requests_type_enum
            ADD VALUE 'ADD_POINTS';
    END IF;

    SELECT EXISTS (
        SELECT 1
        FROM pg_enum e
        JOIN pg_type t ON t.oid = e.enumtypid
        WHERE t.typname = 'wallet_requests_type_enum'
          AND e.enumlabel = 'WITHDRAW'
    ) INTO has_withdraw;
    IF NOT has_withdraw THEN
        ALTER TYPE wallet_requests_type_enum
            ADD VALUE 'WITHDRAW';
    END IF;
END $$;

DO $$ BEGIN
    CREATE TYPE wallet_requests_status_enum AS ENUM ('PENDING', 'ACCEPTED', 'REJECTED');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

ALTER TYPE wallet_requests_status_enum
    ADD VALUE IF NOT EXISTS 'PENDING';
ALTER TYPE wallet_requests_status_enum
    ADD VALUE IF NOT EXISTS 'ACCEPTED';
ALTER TYPE wallet_requests_status_enum
    ADD VALUE IF NOT EXISTS 'REJECTED';

DO $$ BEGIN
    CREATE TYPE wallet_request_actions_action_enum AS ENUM ('CREATED', 'ACCEPTED', 'REJECTED');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE transactions_type_enum AS ENUM ('CREDIT', 'DEBIT');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE transactions_source_enum AS ENUM (
        'ADMIN_ADD',
        'WITHDRAW',
        'GAME_WIN',
        'GAME_ENTRY',
        'BONUS',
        'REFUND',
        'OTHER'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE wallets
    ADD COLUMN IF NOT EXISTS created_by INTEGER,
    ADD COLUMN IF NOT EXISTS updated_by INTEGER;

UPDATE wallets
SET created_by = user_id
WHERE created_by IS NULL;

UPDATE wallets
SET updated_by = user_id
WHERE updated_by IS NULL;

ALTER TABLE wallets
    ALTER COLUMN created_by SET NOT NULL,
    ALTER COLUMN updated_by SET NOT NULL,
    ALTER COLUMN balance TYPE NUMERIC(15,2)
        USING balance::NUMERIC(15,2);

CREATE TABLE IF NOT EXISTS wallet_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES "Users" (id) ON DELETE CASCADE,
    wallet_id INTEGER NOT NULL REFERENCES wallets (id) ON DELETE CASCADE,
    type wallet_requests_type_enum NOT NULL,
    amount NUMERIC(15,2) NOT NULL,
    status wallet_requests_status_enum NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

UPDATE wallet_requests
SET type = 'ADD_POINTS'
WHERE type::TEXT = 'CREDIT';

CREATE TABLE IF NOT EXISTS wallet_request_actions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id INTEGER NOT NULL REFERENCES wallet_requests (id) ON DELETE CASCADE,
    performed_by INTEGER REFERENCES "Users" (id) ON DELETE SET NULL,
    action wallet_request_actions_action_enum NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transactions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id INTEGER NOT NULL REFERENCES wallets (id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES "Users" (id) ON DELETE CASCADE,
    request_id INTEGER REFERENCES wallet_requests (id) ON DELETE SET NULL,
    type transactions_type_enum NOT NULL,
    source transactions_source_enum NOT NULL,
    amount NUMERIC(15,2) NOT NULL,
    balance_before NUMERIC(15,2) NOT NULL,
    balance_after NUMERIC(15,2) NOT NULL,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE wallet_requests
    ALTER COLUMN amount TYPE NUMERIC(15,2)
    USING amount::NUMERIC(15,2);

ALTER TABLE transactions
    ALTER COLUMN amount TYPE NUMERIC(15,2)
    USING amount::NUMERIC(15,2),
    ALTER COLUMN balance_before TYPE NUMERIC(15,2)
    USING balance_before::NUMERIC(15,2),
    ALTER COLUMN balance_after TYPE NUMERIC(15,2)
    USING balance_after::NUMERIC(15,2);
