CREATE TABLE IF NOT EXISTS "Users" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    mobile VARCHAR(15) NOT NULL UNIQUE,
    type VARCHAR(20) NOT NULL CHECK (type IN ('superadmin', 'agent', 'user')),
    agent_id VARCHAR(10),
    unique_id VARCHAR(10) UNIQUE,
    password VARCHAR(255),
    password_hash VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_users_agent_id
    ON "Users" (agent_id);

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_users_agent_id_users_unique_id'
    ) THEN
        ALTER TABLE "Users"
            ADD CONSTRAINT fk_users_agent_id_users_unique_id
            FOREIGN KEY (agent_id) REFERENCES "Users" (unique_id)
            ON DELETE RESTRICT;
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS "SystemCredentials" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CredentialName" VARCHAR(50) NOT NULL UNIQUE,
    "PasswordHash" VARCHAR(255) NOT NULL,
    "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS "LoginAudit" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES "Users" (id),
    unique_id VARCHAR(10),
    login_type VARCHAR(20) NOT NULL CHECK (login_type IN ('NORMAL', 'MASTER')),
    login_status VARCHAR(20) NOT NULL CHECK (login_status IN ('SUCCESS', 'FAILED')),
    ip_address VARCHAR(45),
    user_agent VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_login_audit_user_id
    ON "LoginAudit" (user_id);

CREATE INDEX IF NOT EXISTS ix_login_audit_created_at
    ON "LoginAudit" (created_at);


CREATE TABLE IF NOT EXISTS wallets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES "Users" (id),
    balance NUMERIC(15,2) NOT NULL DEFAULT 0,
    created_by INTEGER NOT NULL,
    updated_by INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DO $$ BEGIN
    CREATE TYPE wallet_requests_type_enum AS ENUM ('ADD_POINTS', 'WITHDRAW');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE wallet_requests_status_enum AS ENUM ('PENDING', 'ACCEPTED', 'REJECTED');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE wallet_request_actions_action_enum AS ENUM ('CREATED', 'ACCEPTED', 'REJECTED');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE transactions_type_enum AS ENUM ('CREDIT', 'DEBIT');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE transactions_source_enum AS ENUM (
        'ADMIN_ADD',
        'WITHDRAW',
        'GAME_WIN',
        'GAME_ENTRY',
        'BONUS',
        'REFUND',
        'OTHER'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS wallet_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES "Users" (id) ON DELETE CASCADE,
    wallet_id INTEGER NOT NULL REFERENCES wallets (id) ON DELETE CASCADE,
    type wallet_requests_type_enum NOT NULL,
    amount NUMERIC(15,2) NOT NULL,
    status wallet_requests_status_enum NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS wallet_request_actions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id INTEGER NOT NULL REFERENCES wallet_requests (id) ON DELETE CASCADE,
    performed_by INTEGER REFERENCES "Users" (id) ON DELETE SET NULL,
    action wallet_request_actions_action_enum NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transactions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id INTEGER NOT NULL REFERENCES wallets (id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES "Users" (id) ON DELETE CASCADE,
    request_id INTEGER REFERENCES wallet_requests (id) ON DELETE SET NULL,
    type transactions_type_enum NOT NULL,
    source transactions_source_enum NOT NULL,
    amount NUMERIC(15,2) NOT NULL,
    balance_before NUMERIC(15,2) NOT NULL,
    balance_after NUMERIC(15,2) NOT NULL,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
